# Generated by Django 6.0.2 on 2026-02-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anetar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=50)),
                ('mbiemri', models.CharField(max_length=50)),
                ('mosha', models.IntegerField()),
                ('data_regjistrimit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
