# Generated by Django 6.0.2 on 2026-02-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anetar',
            name='mbiemri',
        ),
        migrations.RemoveField(
            model_name='anetar',
            name='mosha',
        ),
        migrations.AddField(
            model_name='anetar',
            name='paketa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anetar',
            name='telefoni',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anetar',
            name='emri',
            field=models.CharField(max_length=100),
        ),
    ]
