# Generated by Django 6.0.2 on 2026-02-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0002_remove_anetar_mbiemri_remove_anetar_mosha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anetar',
            name='telefoni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
