# Generated by Django 6.0.2 on 2026-02-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0003_alter_anetar_telefoni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('features', models.TextField()),
                ('duration_months', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='anetar',
            name='telefoni',
            field=models.CharField(default='000-000', max_length=20),
            preserve_default=False,
        ),
    ]
