# Generated by Django 6.0.2 on 2026-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0004_membership_alter_anetar_telefoni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='title',
            new_name='emri',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='price',
        ),
        migrations.AddField(
            model_name='membership',
            name='cmimi',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
