# Generated by Django 6.0.2 on 2026-02-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0005_rename_title_membership_emri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=100)),
                ('pershkrim_i_shkurter', models.CharField(max_length=250)),
                ('pikat_e_klases', models.TextField(help_text='Shkruaj pikat e ndara me Enter')),
                ('imazhi', models.ImageField(upload_to='klasat/')),
            ],
        ),
    ]
