# Generated by Django 6.0.2 on 2026-02-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0006_klasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasa',
            name='pershkrim_i_detajuar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
