# Generated by Django 6.0.2 on 2026-02-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0007_klasa_pershkrim_i_detajuar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klasa',
            options={'verbose_name': 'Klasa', 'verbose_name_plural': 'Klasat'},
        ),
    ]
