# Generated by Django 6.0.2 on 2026-02-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0008_alter_klasa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oraret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dita', models.CharField(choices=[('Hene', 'E Hënë'), ('Marte', 'E Martë'), ('Merkure', 'E Mërkurë'), ('Enjte', 'E Enjte'), ('Premte', 'E Premte'), ('Shtune', 'E Shtunë'), ('Diele', 'E Dielë')], max_length=20)),
                ('ora_fillimit', models.TimeField()),
                ('ora_mbarimit', models.TimeField()),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacion.klasa')),
            ],
            options={
                'verbose_name_plural': 'oraret',
            },
        ),
    ]
