# Generated by Django 6.0.2 on 2026-02-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0009_oraret'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anetar',
            options={'verbose_name': 'Anetar', 'verbose_name_plural': 'Anetaret'},
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='emri',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='cmimi',
        ),
        migrations.AddField(
            model_name='membership',
            name='duration_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
