# Generated by Django 6.0.2 on 2026-02-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0010_alter_anetar_options_rename_emri_membership_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraret',
            name='klasa',
        ),
        migrations.RemoveField(
            model_name='oraret',
            name='ora_fillimit',
        ),
        migrations.RemoveField(
            model_name='oraret',
            name='ora_mbarimit',
        ),
        migrations.AddField(
            model_name='oraret',
            name='emri',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oraret',
            name='ora',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oraret',
            name='salla',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oraret',
            name='dita',
            field=models.CharField(choices=[('E HËNË', 'E HËNË'), ('E MARTË', 'E MARTË'), ('E MËRKURË', 'E MËRKURË'), ('E ENJTE', 'E ENJTE'), ('E PREMTE', 'E PREMTE'), ('E SHTUNË', 'E SHTUNË')], max_length=20),
        ),
    ]
