# Generated by Django 6.0.2 on 2026-02-24 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0011_remove_oraret_klasa_remove_oraret_ora_fillimit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oraret',
            name='ora',
        ),
        migrations.AddField(
            model_name='oraret',
            name='ora_fillimit',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='oraret',
            name='ora_mbarimit',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
