# Generated by Django 6.0.2 on 2026-02-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0012_remove_oraret_ora_oraret_ora_fillimit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraret',
            name='dita',
            field=models.CharField(choices=[('E_HËNË', 'E HËNË'), ('E_MARTË', 'E MARTË'), ('E_MËRKURË', 'E MËRKURË'), ('E_ENJTE', 'E ENJTE'), ('E_PREMTE', 'E PREMTE'), ('E_SHTUNË', 'E SHTUNË')], max_length=20),
        ),
    ]
