# Generated by Django 6.0.2 on 2026-02-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0013_alter_oraret_dita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oraret',
            old_name='emri',
            new_name='klasa',
        ),
    ]
