# Generated by Django 6.0.2 on 2026-02-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0014_rename_emri_oraret_klasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaSuksesit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=30)),
                ('pershkrimi_shkurter', models.CharField(max_length=200)),
                ('foto_para', models.ImageField(upload_to='transformime/')),
                ('foto_pas', models.ImageField(upload_to='trasformime/')),
                ('data_krijimit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
