# Generated by Django 6.0.2 on 2026-02-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0015_historiasuksesit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiasuksesit',
            options={'verbose_name_plural': 'Historite'},
        ),
    ]
