# Generated by Django 6.0.2 on 2026-02-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0016_alter_historiasuksesit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='ambient/')),
                ('pershkrim', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Ambientet',
            },
        ),
    ]
