# Generated by Django 6.0.2 on 2026-02-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0017_ambientet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiasuksesit',
            name='foto_pas',
            field=models.ImageField(upload_to='transformime/'),
        ),
    ]
