# Generated by Django 6.0.2 on 2026-02-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0018_alter_historiasuksesit_foto_pas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anetar',
            options={'verbose_name': 'Regjistrime', 'verbose_name_plural': 'Regjistrimet'},
        ),
        migrations.AlterModelOptions(
            name='historiasuksesit',
            options={'verbose_name': 'Foto Para/Pas', 'verbose_name_plural': 'Foto Para/Pas'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Paketa', 'verbose_name_plural': 'Paketat'},
        ),
    ]
