# Generated by Django 6.0.2 on 2026-02-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0019_alter_anetar_options_alter_historiasuksesit_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoriaSuksesit',
            new_name='HistoriSuksesi',
        ),
    ]
