# Generated by Django 6.0.2 on 2026-03-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0021_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='anetar',
            name='burimi',
            field=models.CharField(default='Paketa', max_length=50),
        ),
        migrations.AddField(
            model_name='anetar',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='anetar',
            name='mesazhi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anetar',
            name='telefoni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
