# Generated by Django 6.0.2 on 2026-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0022_anetar_burimi_anetar_email_anetar_mesazhi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klasa',
            name='intensiteti',
            field=models.CharField(default='I Lartë', max_length=50),
        ),
        migrations.AddField(
            model_name='klasa',
            name='kohezgjatja',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='klasa',
            name='target_group',
            field=models.CharField(default='Gjithësecili', help_text='P.sh. Fillestarë, Sportistë Elite, etj.', max_length=100),
        ),
    ]
