# Generated by Django 6.0.2 on 2026-03-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplikacion', '0023_klasa_intensiteti_klasa_kohezgjatja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='e_rekomanduar',
            field=models.BooleanField(default=False),
        ),
    ]
